project:
  name: aws-linux-bastion
  owner: andy.stevko@brainome.ai
  lambda_source_path: functions/source
  lambda_zip_path: packages
  regions:
  - us-east-1
  - us-east-2
  template: templates/linux-bastion-master.template
  parameters:
    AvailabilityZones: $[taskcat_getaz_2]
    BastionInstanceType: t3.small
    KeyPairName: $[taskcat_getkeypair]
    PrivateSubnet1CIDR: 10.0.0.0/19
    PrivateSubnet2CIDR: 10.0.32.0/19
    PublicSubnet1CIDR: 10.0.128.0/20
    PublicSubnet2CIDR: 10.0.144.0/20
    QSS3BucketName: download.brainome.net
    QSS3KeyPrefix: brainome-dev
    RemoteAccessCIDR: 0.0.0.0/32
    VPCCIDR: 10.0.0.0/16
    QSS3BucketRegion: $[taskcat_current_region]
tests:
  amznlinux2hvm:
    parameters:
      BastionAMIOS: Amazon-Linux2-HVM
    regions:
      - us-east-1
      - us-east-2
  centos7hvm:
    parameters:
      BastionAMIOS: CentOS-7-HVM
    regions:
      - us-east-1
      - us-east-2
  sles15hvm:
    parameters:
      BastionAMIOS: SUSE-SLES-15-HVM
  us1604hvm:
    parameters:
      BastionAMIOS: Ubuntu-Server-16.04-LTS-HVM
  us1804hvm:
    parameters:
      BastionAMIOS: Ubuntu-Server-18.04-LTS-HVM
